
services:  

  mysite:  
    container_name: mysite
    build:   
      context: .
      dockerfile: ./Dockerfile
    volumes:  
      - ./.:/code
      - ./build:/code/static
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
      - postgres
    
  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - cache:/data
    
  postgres:
    container_name: postgres
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - /postgres-data:/var/lib/postgresql/data
      - /postgres-data-backups:/backups
    env_file:
      - .env
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  cache:
    driver: local
  postgres-data: {}
  postgres-data-backups: {}

networks:
  my_network:
    driver: bridge
