import { Col, Image, Flex, Row, Typography } from 'antd';
import { Link } from 'react-router-dom';

const { Title, Text, Paragraph } = Typography;


export default function Privacy() {

    return (
        <>
            <Title style={{textAlign: 'center'}}>
                Privacy Policy
            </Title>
            <Paragraph>
                Last updated: August 30, 2024
            </Paragraph>
            <Paragraph>
                This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about 
                Your privacy rights and how the law protects You.
            </Paragraph>
            <Paragraph>
                We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this 
                Privacy Policy.
            </Paragraph>

            <Title level={2}>Interpretation and Definitions</Title>
            <Title level={3}>Interpretation</Title>
            <Paragraph>
                The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning 
                regardless of whether they appear in singular or in plural.</Paragraph>
            <Title level={3}>Definitions</Title>
            <Paragraph>
                For the purposes of this Privacy Policy:
            </Paragraph>
            <ul>
                <li>
                    <Paragraph>
                        <Text strong>Account</Text> means a unique account created for You to access our Service or parts of our Service.
                    </Paragraph>
                </li>
                <li>
                    <Paragraph>
                        <Text strong>Affiliate</Text> means an entity that controls, is controlled by or is under common control with a party, where &quot;control&quot; means 
                        ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.
                    </Paragraph>
                </li>
                <li>
                    <Paragraph>
                        <Text strong>Company</Text> (referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Agreement) refers 
                        to Viswamedha Nalabotu.
                    </Paragraph>
                </li>
                <li>
                    <Paragraph>
                        <Text strong>Cookies</Text> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details 
                        of Your browsing history on that website among its many uses.
                    </Paragraph>
                </li>
                <li>
                    <Paragraph>
                        <Text strong>Country</Text> refers to:  United Kingdom
                    </Paragraph>
                </li>
                <li>
                    <Paragraph>
                        <Text strong>Device</Text> means any device that can access the Service such as a computer, a cellphone or a digital tablet.
                    </Paragraph>
                </li>
                <li>
                    <Paragraph>
                        <Text strong>Personal Data</Text> is any information that relates to an identified or identifiable individual.
                    </Paragraph>
                </li>
                <li>
                    <Paragraph>
                        <Text strong>Service</Text> refers to the Website.
                    </Paragraph>
                </li>
                <li>
                    <Paragraph>
                        <Text strong>Service Provider</Text> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party 
                        companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services 
                        related to the Service or to assist the Company in analyzing how the Service is used.
                    </Paragraph>
                </li>
                <li>
                    <Paragraph>
                        <Text strong>Usage Data</Text> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure 
                        itself (for example, the duration of a page visit).
                    </Paragraph>
                </li>
                <li>
                    <Paragraph>
                        <Text strong>Website</Text> refers to Viswamedha Nalabotu, accessible from 
                        <Link href="/" rel="external nofollow noopener" target="_blank">https://www.viswamedha.com</Link>
                    </Paragraph>
                </li>
                <li>
                    <Paragraph>
                        <Text strong>You</Text> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual 
                        is accessing or using the Service, as applicable.
                    </Paragraph>
                </li>
            </ul>

            <Title level={2}>
                Collecting and Using Your Personal Data
            </Title>
            <Title level={3}>
                Types of Data Collected
            </Title>
            <Title level={4}>
                Personal Data
            </Title>
            <Paragraph>
                While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally 
                identifiable information may include, but is not limited to:
            </Paragraph>
            <ul>
                <li>
                    <Paragraph>
                        Email address
                    </Paragraph>
                </li>
                <li>
                    <Paragraph>
                        First name and last name
                    </Paragraph>
                </li>
                <li>
                    <Paragraph>
                        Usage Data
                    </Paragraph>
                </li>
            </ul>
            <Title level={4}>
                Usage Data
            </Title>
            <Paragraph>
                Usage Data is collected automatically when using the Service.
            </Paragraph>
            <Paragraph>
                Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that 
                You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
            </Paragraph>
            <Paragraph>
                When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile 
                device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, 
                unique device identifiers and other diagnostic data.
            </Paragraph>
            <Paragraph>
                We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.</Paragraph>
            <Title level={4}>
                Tracking Technologies and Cookies
            </Title>
            <Paragraph>
                We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, 
                tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:
            </Paragraph>
            <ul>
                <li>
                    <Paragraph>
                        <Text strong>Cookies or Browser Cookies.</Text> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.
                    </Paragraph>
                </li>
                <li>
                    <Paragraph>
                        <Text strong>Web Beacons.</Text> Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).
                    </Paragraph>
                </li>
            </ul>
            <Paragraph>Cookies can be &quot;Persistent&quot; or &quot;Session&quot; Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go 
                offline, while Session Cookies are deleted as soon as You close Your web browser.
            </Paragraph>
            <Paragraph>
                We use both Session and Persistent Cookies for the purposes set out below:
            </Paragraph>
            <ul>
                <li>
                    <Paragraph>
                        <Text strong>Necessary / Essential Cookies</Text>
                    </Paragraph>
                    <Paragraph>
                        Type: Session Cookies
                    </Paragraph>
                    <Paragraph>
                        Administered by: Us
                    </Paragraph>
                    <Paragraph>
                        Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to 
                        authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only 
                        use these Cookies to provide You with those services.
                    </Paragraph>
                </li>
                <li>
                    <Paragraph>
                        <Text strong>Cookies Policy / Notice Acceptance Cookies</Text>
                    </Paragraph>
                    <Paragraph>
                        Type: Persistent Cookies
                    </Paragraph>
                    <Paragraph>
                        Administered by: Us
                    </Paragraph>
                    <Paragraph>
                        Purpose: These Cookies identify if users have accepted the use of cookies on the Website.
                    </Paragraph>
                </li>
                <li>
                    <Paragraph>
                        <Text strong>Functionality Cookies</Text>
                    </Paragraph>
                    <Paragraph>
                        Type: Persistent Cookies
                    </Paragraph>
                    <Paragraph>
                        Administered by: Us
                    </Paragraph>
                    <Paragraph>
                        Purpose: These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose 
                        of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website.
                    </Paragraph>
                </li>
            </ul>
            
            <Title level={3}>
                Use of Your Personal Data
            </Title>
            <Paragraph>
                The Company may use Personal Data for the following purposes:
            </Paragraph>
            <ul>
                <li>
                    <Paragraph>
                        <Text strong>To provide and maintain our Service</Text>, including to monitor the usage of our Service.
                    </Paragraph>
                </li>
                <li>
                    <Paragraph>
                        <Text strong>To manage Your Account:</Text> to manage Your registration as a user of the Service. The Personal Data You provide can give You access to 
                        different functionalities of the Service that are available to You as a registered user.
                    </Paragraph>
                </li>
                <li>
                    <Paragraph>
                        <Text strong>For the performance of a contract:</Text> the development, compliance and undertaking of the purchase contract for the products, items or 
                        services You have purchased or of any other contract with Us through the Service.
                    </Paragraph>
                </li>
                <li>
                    <Paragraph>
                        <Text strong>To contact You:</Text> To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile 
                        application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.
                    </Paragraph>
                </li>
                <li>
                    <Paragraph>
                        <Text strong>To provide You</Text> with news, special offers and general information about other goods, services and events which we offer that are 
                        similar to those that you have already purchased or enquired about unless You have opted not to receive such information.
                    </Paragraph>
                </li>
                <li>
                    <Paragraph>
                        <Text strong>To manage Your requests:</Text> To attend and manage Your requests to Us.
                    </Paragraph>
                </li>
                <li>
                    <Paragraph>
                        <Text strong>For business transfers:</Text> We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, 
                        dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar 
                        proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.
                    </Paragraph>
                </li>
                <li>
                    <Paragraph>
                        <Text strong>For other purposes</Text>: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the 
                        effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.
                    </Paragraph>
                </li>
            </ul>
            <Paragraph>
                We may share Your personal information in the following situations:
            </Paragraph>
            <ul>
                <li>
                    <Paragraph>
                        <Text strong>With Service Providers:</Text> We may share Your personal information with Service Providers to monitor and analyze the use of our Service,  to contact You.
                    </Paragraph>
                </li>
                <li>
                    <Paragraph>
                        <Text strong>For business transfers:</Text> We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.
                    </Paragraph>
                </li>
                <li>
                    <Paragraph>
                        <Text strong>With Affiliates:</Text> We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us.
                    </Paragraph>
                </li>
                <li>
                    <Paragraph>
                        <Text strong>With business partners:</Text> We may share Your information with Our business partners to offer You certain products, services or promotions.
                    </Paragraph>
                </li>
                <li>
                    <Paragraph>
                        <Text strong>With other users:</Text> when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside.
                    </Paragraph>
                </li>
                <li>
                    <Paragraph>
                        <Text strong>With Your consent</Text>: We may disclose Your personal information for any other purpose with Your consent.
                    </Paragraph>
                </li>
            </ul>

            <Title level={3}>
                Retention of Your Personal Data
            </Title>
            <Paragraph>
                The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal 
                Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve 
                disputes, and enforce our legal agreements and policies.
            </Paragraph>
            <Paragraph>
                The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is 
                used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.
            </Paragraph>

            <Title level={3}>
                Transfer of Your Personal Data
            </Title>
            <Paragraph>
                Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing 
                are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other 
                governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.
            </Paragraph>
            <Paragraph>
                Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.
            </Paragraph>
            <Paragraph>
                The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of 
                Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other 
                personal information.
            </Paragraph>

            <Title level={3}>
                Delete Your Personal Data
            </Title>
            <Paragraph>
                You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.
            </Paragraph>
            <Paragraph>
                Our Service may give You the ability to delete certain information about You from within the Service.
            </Paragraph>
            <Paragraph>
                You may update, amend, or delete Your information at any time by signing in to Your Account, if you have one, and visiting the account settings section that 
                allows you to manage Your personal information. You may also contact Us to request access to, correct, or delete any personal information that You have provided 
                to Us.
            </Paragraph>
            <Paragraph>
                Please note, however, that We may need to retain certain information when we have a legal obligation or lawful basis to do so.
            </Paragraph>

            <Title level={3}>
                Disclosure of Your Personal Data
            </Title>
            <Title level={4}>
                Business Transactions
            </Title>
            <Paragraph>
                If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is 
                transferred and becomes subject to a different Privacy Policy.
            </Paragraph>
            <Title level={4}>
                Law enforcement
            </Title>
            <Paragraph>
                Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public 
                authorities (e.g. a court or a government agency).
            </Paragraph>
            <Title level={4}>
                Other legal requirements
            </Title>
            <Paragraph>
                The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:
            </Paragraph>
            <ul>
                <li>
                    Comply with a legal obligation
                </li>
                <li>
                    Protect and defend the rights or property of the Company
                </li>
                <li>
                    Prevent or investigate possible wrongdoing in connection with the Service
                </li>
                <li>
                    Protect the personal safety of Users of the Service or the public
                </li>
                <li>
                    Protect against legal liability
                </li>
            </ul>
            
            <Title level={3}>
                Security of Your Personal Data
            </Title>
            <Paragraph>
                The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. 
                While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.
            </Paragraph>
            
            <Title level={2}>
                Links to Other Websites
            </Title>
            <Paragraph>
                Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. 
                We strongly advise You to review the Privacy Policy of every site You visit.
            </Paragraph>
            <Paragraph>
                We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.
            </Paragraph>

            <Title level={2}>
                Changes to this Privacy Policy
            </Title>
            <Paragraph>
                We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.
            </Paragraph>
            <Paragraph>
                We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the &quot;Last updated&quot; date at the top 
                of this Privacy Policy.
            </Paragraph>
            <Paragraph>
                You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
            </Paragraph>
            
            <Title level={2}>
                Contact Us
            </Title>
            <Paragraph>
                If you have any questions about this Privacy Policy, You can contact us:
            </Paragraph>
            <ul>
                <li>
                    <Paragraph>
                        By email: nalabotuviswamedha@gmail.com
                    </Paragraph>
                </li>
                <li>
                    <Paragraph>
                        By visiting this page on our website: <Link to="/contact/" rel="external nofollow noopener" target="_blank">https://www.viswamedha.com/contact/</Link>
                    </Paragraph>
                </li>
            </ul>
        </>
    )
}