# Generated by Django 5.1.2 on 2024-10-18 15:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('post_uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='User UUID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Title')),
                ('heading', models.CharField(blank=True, max_length=255, verbose_name='Heading')),
                ('subheading', models.CharField(blank=True, max_length=255, verbose_name='Subheading')),
                ('content', models.TextField(verbose_name='Content')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/images/', verbose_name='Image')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('meta_description', models.CharField(default='', max_length=255, verbose_name='Meta Description')),
                ('published', models.BooleanField(default=False, verbose_name='Published')),
                ('publish_date', models.DateField(blank=True, null=True, verbose_name='Publish Date')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='blog.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
