# Generated by Django 5.1.2 on 2024-10-18 16:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='photos')),
                ('alt', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('path', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Reference UUID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Name')),
                ('value', models.CharField(max_length=1024, verbose_name='Value')),
            ],
            options={
                'verbose_name': 'Reference',
                'verbose_name_plural': 'References',
            },
        ),
    ]
