# Generated by Django 5.1.2 on 2024-12-22 12:46

import apps.chat.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tutor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('room_uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Room UUID')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Message UUID')),
                ('content', models.CharField(max_length=512)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DirectChat',
            fields=[
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='direct_chat', serialize=False, to='chat.room')),
                ('limit', models.IntegerField(default=2, editable=False, verbose_name='Limit')),
                ('online', models.ManyToManyField(blank=True, related_name='direct_online_rooms', to=settings.AUTH_USER_MODEL, verbose_name='Online')),
                ('users', models.ManyToManyField(blank=True, related_name='direct_rooms', to=settings.AUTH_USER_MODEL, verbose_name='Users')),
            ],
            options={
                'verbose_name': 'Chat',
                'verbose_name_plural': 'Chats',
            },
            bases=('chat.room',),
        ),
        migrations.CreateModel(
            name='GroupChat',
            fields=[
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='group_chat', serialize=False, to='chat.room')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('limit', models.IntegerField(default=10, verbose_name='Limit')),
                ('invite_code', models.CharField(default=apps.chat.models.get_random_code, max_length=8, unique=True, verbose_name='Invite Code')),
                ('online', models.ManyToManyField(blank=True, related_name='group_online_rooms', to=settings.AUTH_USER_MODEL, verbose_name='Online')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms_owned', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('staff', models.ManyToManyField(blank=True, related_name='staff_rooms', to=settings.AUTH_USER_MODEL, verbose_name='Staff')),
                ('users', models.ManyToManyField(blank=True, related_name='group_rooms', to=settings.AUTH_USER_MODEL, verbose_name='Users')),
            ],
            options={
                'verbose_name': 'Group Chat',
                'verbose_name_plural': 'Group Chats',
            },
            bases=('chat.room',),
        ),
        migrations.CreateModel(
            name='StudentChat',
            fields=[
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chat.room')),
                ('group', models.BooleanField(default=False, editable=False, verbose_name='Group')),
                ('limit', models.IntegerField(default=2, verbose_name='Limit')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_rooms', to='tutor.student', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Student Chat',
                'verbose_name_plural': 'Student Chats',
            },
            bases=('chat.room',),
        ),
    ]
